-- 고양이와 개는 몇마리 있을까
SELECT ANIMAL_TYPE, count(ANIMAL_TYPE)
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE ASC

-- 동명 동물 수 찾기
SELECT NAME, COUNT(NAME) as COUNT
FROM ANIMAL_INS
where NAME IS NOT NULL
GROUP BY NAME
having COUNT(NAME) >= 2
ORDER BY NAME

-- 입양 시각 구하기 (1)
SELECT HOUR(DATETIME) , COUNT(HOUR(DATETIME))
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >= 9 and HOUR(DATETIME)  < 20
GROUP BY HOUR(DATETIME) 
ORDER BY hour(Datetime)