-- 모든 레코드 조회하기
SELECT * FROM ANIMAL_INS order by ANIMAL_ID ASC;

-- 역순 정렬하기
SELECT NAME, DATETIME FROM ANIMAL_INS ORDER BY ANIMAL_ID DESC;

-- 아픈동물 찾기
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION = "Sick";

-- 어린동물 찾기
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION <> "Aged";

-- 동물의 아이디와 이름
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS ORDER BY ANIMAL_ID ASC;

-- 여러 기준으로 정렬하기
SELECT ANIMAL_ID, NAME, DATETIME 
FROM ANIMAL_INS 
ORDER by NAME asc, DATETIME desc


-- 상위 n개 레코드 (limit 사용함)
SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME limit 1;
SELECT NAME FROM animal_ins WHERE DATETIME in (select min(datetime) from animal_ins)


